name: 'Update card in click up'
description: 'With this action after every merge is closed in github you will be able to update your cards in the click up'
author: 'luis12391'
inputs:
  comments:
    required: true
    default: "N/A"
runs:
  using: 'docker'
  image: 'Dockerfile'
