name: 'Update card in click up'
description: 'With this action you will be able to update your cards in the click up after when a merges is closed in github'
author: 'luis12391'
inputs:
  comments:
    required: false
    default: "Without commmnets"
runs:
  using: 'docker'
  image: 'Dockerfile'
