name: Discord message
on:
  push # github.event_name == issue_comment
        
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Publish comment
      uses: ./ # Uses an action in the root directory
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comments: "Preuab"